server:
  port: 8082

# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev

---
# 开发环境配置
spring:
  profiles: dev
mysql:
  ipPort: localhost:3306
  
---
# 测试环境配置
spring:
  profiles: test
mysql:
  ipPort: 192.168.0.12:8066
  
---
# 生产环境配置
spring:
  profiles: prod
mysql:
  ipPort: 192.168.0.13:8066